language: node_js
node_js:
    - "6.9.0"
    - "8.5.0"

install:
    - npm install .
    - curl -sL -o ./kelda https://github.com/kelda/kelda/releases/download/dev/kelda_linux
        && chmod +x ./kelda

before_script:
    - npm install -g gulp-cli

script:
    - gulp lint
    - mkdir -p ~/.kelda/infra/ && mv ./testInfra.js ~/.kelda/infra/default.js
    - ./kelda inspect ./sparkRun.js graphviz

notifications:
    slack:
        secure: dCL7nsgc3ybUPp96H1tQLyY+OH7rVLpC9lpj63nugjE0Rt65iztjmZEpXSfYfzc1FeRlbssuFyR4uDBsAEIxU09/TqX//RXP+LdvzIXRrTXsh8dbyyFE4K490Gh9WWY7tRup3es9NQsv7USw+SFS/AooIEZaw8E4n4p5PZ6YBN5iSMMjyeoS8wMLi+LI0Ae9q9TeqhNH1pMvsMZvsKWOVXlSlhTIB/X+2QEbCgH9+ETO8wgJ2Ll9mzfXrBa0j5lvoVKQn+uzfboGRIxEY6ab05JraJVV/vv9NHCSVRhsVwIk7YDCptLyufdGdW48vf1yym4owqTnkQ5VdsyzDdbZ1UyuZjbvGucxhjPcH7p+CbWagUGOg7f1MZZzXSWQnk1iswIHsgQaIaTRCfo4+X0HTkcH25xj0OwvzxcNzQwuqZW3HXnhagtr2UtUDVC2XHbGEucy3NHmBNYHbDQ2ZyanmeznHfA+OdEMjNDtCQI2rlagOD12K+Rjreqt06TeKVngZTlxchbMi1CzoO0nTHlwKuGn3+Vgc8bsaok4HMmp6XVfDLRnKlvmcFNJVT03PWOaQ+qSEEk99sV01gaq/WL3gfAwBGXVsfFWLT0Uo0XHebrIrLJOPyw/xy8WGAHMptxu3mYvk5Z/Gz1R3OPjF0jvBcHv0PB2qi7AtXPmUmUukuE=
