#!/usr/bin/python

import argparse
import os
import socket
import subprocess
import time
import sys
import urllib2
import string


def worker():
    if "MASTER" not in os.environ:
        print "Workers require MASTER environment variable."
        sys.exit(1)

    subprocess.check_call(["/spark/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker", os.environ["MASTER"]])


def main():
    parser = argparse.ArgumentParser(description='Kelda Spark Init Script')
    parser.add_argument("role", choices=["master", "worker"])
    args = parser.parse_args()

    publicIP = urllib2.urlopen("http://checkip.amazonaws.com/").read()
    publicIP = string.strip(publicIP)

    os.environ["SPARK_PUBLIC_DNS"] = publicIP

    if args.role == "master":
        subprocess.check_call(["/spark/bin/spark-class",
            "org.apache.spark.deploy.master.Master"])
    elif args.role == "worker":
        worker()

try:
    main()
except KeyboardInterrupt:
    pass
